### ISSUE TITLE
API change (PublisherInfo)

### ISSUE THREAD

**Issue by Chman** [LostPolygon/Unity-Publisher-API-PHP#4]
```
Notice: Undefined property: stdClass::$long_url in /[redacted]/AssetStorePublisherClient.class.php on line 407
```

In `PUBLISHER_OVERVIEW_JSON_URL` the `long_url` entry doesn't exist anymore. It doesn't seem to have been replaced by anything so I think it can be safely removed.

**Comment by LostPolygon** [comment]
Thanks, I've removed it and the corresponding method.
