### ISSUE TITLE
They updated the site yesterday.

### ISSUE THREAD

**Issue by AlexBarbulescu** [LostPolygon/Unity-Publisher-API-PHP#5]
Unity Asset Store was updated yesterday with the new "upgrades" now I'm getting this error

Fatal error: Uncaught exception 'AssetStore\AssetStoreException' with message 'Fetching publisher data failed, error code 401 (Unauthorized)' in /var/www/AssetStorePublisherClient.class.php:310 Stack trace: #0 /var/www/AssetStorePublisherClient.class.php(80): AssetStore\Client::AssertHttpCode('Fetching publis...', 401) #1 /var/www/DemoPage.php(61): AssetStore\Client->GetPublisherInfo() #2 {main} thrown in /var/www/AssetStorePublisherClient.class.php on line 310

**Comment by AlexTNT** [comment]
Seems like $store->LoginWithToken('put your token here'); does not work anymore, I've updated with a new token yet the problem persist
it works with  $store->Login('your@publisher.email.com', 'password');

**Comment by LostPolygon** [comment]
Thanks for reporting. I'll only be back in a week, so for now, use the email/password authentication method as a workaround.

**Comment by AlexBarbulescu** [comment]
Any update regarding this?

**Comment by LostPolygon** [comment]
Ah, sorry, totally forgot about this. I'll see what I can do now.

**Comment by LostPolygon** [comment]
Just checked and it works fine for me. In fact, there is no way it can't work: as you can see from the code, `$store->Login` is identical to getting a token and calling `$store->LoginWithToken`:

```
    public function LoginWithToken($token) {
        $this->AssertIsNotLoggedIn();
        $this->loginToken = $token;
        $this->isLoggedIn = true;
        $this->cookies['xunitysession'] = $this->GetXUnitySessionCookie();
    }
    public function Login($user, $password) {
        $this->AssertIsNotLoggedIn();
        $token = $this->GetLoginToken($user, $password);
        $this->LoginWithToken($token);
        return $token;
    }
```

Recheck if you are storing the token correctly.
