### ISSUE TITLE
Fatal error.

### ISSUE THREAD

**Issue by AlexBarbulescu** [LostPolygon/Unity-Publisher-API-PHP#6]
Can you please verify it there's any problem, I'm getting Fatal error starting today. Logged in with user and password not token.
`Fatal error: Uncaught exception 'AssetStore\AssetStoreException' with message 'Fetching publisher data failed, error code 401 (Unauthorized)' in /var/www/AssetStorePublisherClient.class.php:310 Stack trace: #0 /var/www/AssetStorePublisherClient.class.php(80): AssetStore\Client::AssertHttpCode('Fetching publis...', 401) #1 /var/www/DemoPage.php(62): AssetStore\Client->GetPublisherInfo() #2 {main} thrown in /var/www/AssetStorePublisherClient.class.php on line 310`

**Comment by AlexBarbulescu** [comment]
They indeed updated the login. Confirmation here https://groups.google.com/a/unity3d.com/forum/#!topic/assetstorepublishers/HkDAdvntIYo

**Comment by LostPolygon** [comment]
Oh well. Got something fixing to do then.

**Comment by AlexBarbulescu** [comment]
I will be grateful and I really appreciate it. My statistic code relies on this. And it's far from my reach of knowledge to fix it.
Thanks for your hard work.

Alex Barbulescu

**Comment by LostPolygon** [comment]
@AlexBarbulescu 
Fixed in https://github.com/LostPolygon/Unity-Publisher-API-PHP/commit/fa4da08bd431fe7bfdd4ba495e18b6666b4b395d.
