### ISSUE TITLE
Installation Steps Notes

### ISSUE THREAD

**Issue by voxelbusters** [LostPolygon/Unity-Publisher-API-PHP#9]
Hi,
    Thanks a lot for making the code open source and sharing :)

Is it possible to give few steps on how to install this script? I tried hosting on my server but its throwing some weird errors.

`Parse error: syntax error, unexpected T_STRING in /....../AssetStorePublisherClient.class.php on line 520
`

**Comment by ZimM-LostPolygon** [comment]
Added the requirements to the README file.
